export const Users = [
  {
    id: 1,
    profilePicture: "person/001.jpeg",
    username: "Dammy Oyeduns",
  },
  {
    id: 2,
    profilePicture: "person/002.jpeg",
    username: "Ajarat Azzez",
  },
  {
    id: 3,
    profilePicture: "person/003.jpeg",
    username: "Haroon",
  },
  {
    id: 4,
    profilePicture: "person/004.jpeg",
    username: "Zubby",
  },
  {
    id: 5,
    profilePicture: "person/005.jpeg",
    username: "Anas Nuhu",
  },
  {
    id: 6,
    profilePicture: "person/006.jpeg",
    username: "Efe Salubi",
  },
  {
    id: 7,
    profilePicture: "person/007.jpeg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "person/008.jpeg",
    username: "Mrs. Zainab",
  },
  {
    id: 9,
    profilePicture: "person/009.jpeg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "person/010.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/001.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/002.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/003.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/004.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/005.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/006.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/007.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/008.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/009.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/010.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
